version: "3"

services:
  release:
    image: tons/ci-server:${TAG}
    build: .
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      REGISTRY_USER=${REGISTRY_USER}
      REGISTRY_PASS=${REGISTRY_PASS}
      REGISTRY_HOST=${REGISTRY_HOST}
